#! python
def read_fasta(file_name):
    sequences = []
    with open(file_name, 'r') as file:
        seq = ''
        for line in file:
            if line.startswith('>'):
                if seq != '':
                    sequences.append(seq)
                    seq = ''
            else:
                seq += line.strip()
        sequences.append(seq)
    return sequences

file_name = 'example.fasta'
sequences = read_fasta(file_name)
print(sequences)
